services:
  hass-sysinfo:
    image: klaspihl/hass-sysinfo:latest
    container_name: hass-sysinfo
    environment:
      # MQTT configuration
      - MQTT_HOST=mqtt-broker #Replace with your MQTT broker address
      - MQTT_PORT=1883
      #- HA_DISCOVERY_BASE=homeassistant/sensor
      
      # Device information
      - HOSTNAME=${HOSTNAME} #Use the host's hostname as the device name in Home Assistant
      #- MANUFACTURER=Lenovo
      #- MODEL=ThinkPad X1 Carbon Gen 9
      #- SUGGESTED_AREA=Office
      #- SERIAL=1234567890
      
      # Sensor configuration
      #- POLL_FREQUENCY=60 #Polling frequency in seconds. Default is 60 seconds.
      #- MOUNT_POINTS=/,/boot #Additional mount points to monitor for disk usage and age. Default is root (/) only.
      #- MOUNT_FILEAGE=/boot #Monitor file age on this mount point. 
      #- DEBUG=true
      #- SENSOR_EXPIRE=60 #Default value POLL_FREQUENCY * 3
      #- SENSOR_DISKAGE_EXPIRE=600 #Default value POLL_FREQUENCY * 10
    volumes:
      - /:/host:ro,rslave
    restart: unless-stopped
